package kr.co.inter_musica.domain.enums;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "INVALID_REQUEST"),

    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),

    FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
    TEAM_FORBIDDEN(HttpStatus.FORBIDDEN, "TEAM_FORBIDDEN"),
    JOIN_REQUEST_FORBIDDEN(HttpStatus.FORBIDDEN, "JOIN_REQUEST_FORBIDDEN"),

    NOT_FOUND(HttpStatus.NOT_FOUND, "NOT_FOUND"),
    TEAM_NOT_FOUND(HttpStatus.NOT_FOUND, "TEAM_NOT_FOUND"),
    POSITION_NOT_FOUND(HttpStatus.NOT_FOUND, "POSITION_NOT_FOUND"),
    JOIN_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "JOIN_REQUEST_NOT_FOUND"),
    PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, "PROFILE_NOT_FOUND"),

    EMAIL_DUPLICATED(HttpStatus.CONFLICT, "EMAIL_DUPLICATED"),
    JOIN_REQUEST_REGION_MISMATCH(HttpStatus.CONFLICT, "JOIN_REQUEST_REGION_MISMATCH"),
    JOIN_REQUEST_INSTRUMENT_MISMATCH(HttpStatus.CONFLICT, "JOIN_REQUEST_INSTRUMENT_MISMATCH"),
    JOIN_REQUEST_LEVEL_MISMATCH(HttpStatus.CONFLICT, "JOIN_REQUEST_LEVEL_MISMATCH"),
    JOIN_REQUEST_DUPLICATED(HttpStatus.CONFLICT, "JOIN_REQUEST_DUPLICATED"),
    JOIN_REQUEST_CANNOT_CANCEL_NOT_APPLIED(HttpStatus.CONFLICT, "JOIN_REQUEST_CANNOT_CANCEL_NOT_APPLIED"),
    JOIN_REQUEST_CANNOT_DECIDE_NOT_APPLIED(HttpStatus.CONFLICT, "JOIN_REQUEST_CANNOT_DECIDE_NOT_APPLIED"),
    POSITION_CAPACITY_FULL(HttpStatus.CONFLICT, "POSITION_CAPACITY_FULL"),
    ALREADY_TEAM_MEMBER(HttpStatus.CONFLICT, "ALREADY_TEAM_MEMBER"),

    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR");

    private final HttpStatus status;
    private final String message;

    ErrorCode(HttpStatus status, String message) {
        this.status = status;
        this.message = message;
    }

    public HttpStatus getStatus() {
        return status;
    }

    public String getMessage() {
        return message;
    }
}
