package kr.co.inter_musica.presentation.exception;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    INVALID_REQUEST(HttpStatus.BAD_REQUEST, "INVALID_REQUEST"),
    UNAUTHORIZED(HttpStatus.UNAUTHORIZED, "UNAUTHORIZED"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "FORBIDDEN"),
    NOT_FOUND(HttpStatus.NOT_FOUND, "NOT_FOUND"),
    CONFLICT(HttpStatus.CONFLICT, "CONFLICT"),
    EMAIL_DUPLICATED(HttpStatus.CONFLICT, "EMAIL_DUPLICATED"),
    INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "INVALID_CREDENTIALS"),
    INTERNAL_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "INTERNAL_ERROR"),
    TEAM_NOT_FOUND(HttpStatus.NOT_FOUND, "TEAM_NOT_FOUND"),
    POSITION_NOT_FOUND(HttpStatus.NOT_FOUND, "POSITION_NOT_FOUND"),
    JOIN_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "JOIN_REQUEST_NOT_FOUND"),
    PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, "PROFILE_NOT_FOUND"),

    TEAM_FORBIDDEN(HttpStatus.FORBIDDEN, "TEAM_FORBIDDEN"),
    JOIN_REQUEST_FORBIDDEN(HttpStatus.FORBIDDEN, "JOIN_REQUEST_FORBIDDEN"),

    JOIN_REQUEST_REGION_MISMATCH(HttpStatus.CONFLICT, "JOIN_REQUEST_REGION_MISMATCH"),
    JOIN_REQUEST_INSTRUMENT_MISMATCH(HttpStatus.CONFLICT, "JOIN_REQUEST_INSTRUMENT_MISMATCH"),
    JOIN_REQUEST_LEVEL_MISMATCH(HttpStatus.CONFLICT, "JOIN_REQUEST_LEVEL_MISMATCH"),
    JOIN_REQUEST_DUPLICATED(HttpStatus.CONFLICT, "JOIN_REQUEST_DUPLICATED"),
    JOIN_REQUEST_CANNOT_CANCEL_NOT_APPLIED(HttpStatus.CONFLICT, "JOIN_REQUEST_CANNOT_CANCEL_NOT_APPLIED"),
    JOIN_REQUEST_CANNOT_DECIDE_NOT_APPLIED(HttpStatus.CONFLICT, "JOIN_REQUEST_CANNOT_DECIDE_NOT_APPLIED"),
    POSITION_CAPACITY_FULL(HttpStatus.CONFLICT, "POSITION_CAPACITY_FULL"),
    ALREADY_TEAM_MEMBER(HttpStatus.CONFLICT, "ALREADY_TEAM_MEMBER");

    private final HttpStatus status;
    private final String code;

    ErrorCode(HttpStatus status, String code) {
        this.status = status;
        this.code = code;
    }

    public HttpStatus status() { return status; }
    public String code() { return code; }
}
